"""
Alert Engine: Hybrid alert system combining rules and LLM-based analysis
"""
from typing import Dict, List, Any, Optional
from dataclasses import dataclass
from datetime import datetime, timedelta

try:
    from sentence_transformers import SentenceTransformer, util
except ImportError:
    SentenceTransformer = None
    util = None

try:
    from .config import ALERT_RULE_CONFIG
except ImportError:
    from config import ALERT_RULE_CONFIG


@dataclass
class Alert:
    """Alert generated by the system"""
    frame_id: int
    alert_type: str  # "loitering", "repeat_visit", "unusual_time", etc.
    severity: str  # LOW, MEDIUM, HIGH, CRITICAL
    threat_score: int  # 1-10
    message: str
    timestamp: str
    location: str


class AlertEngine:
    """
    Hybrid alert system with rule-based and LLM-enhanced layers.
    
    Rule Layer: Hard triggers based on predefined rules
    LLM Layer: Contextual analysis using frame history
    """

    def __init__(self, config=ALERT_RULE_CONFIG, vlm_processor=None, llm_processor=None):
        self.config = config
        self.alerts: List[Alert] = []
        self.frame_history: Dict[int, Dict[str, Any]] = {}
        self.vlm_processor = vlm_processor
        self.llm_processor = llm_processor
        
        self.embed_model = None
        if SentenceTransformer is not None:
            try:
                self.embed_model = SentenceTransformer("all-MiniLM-L6-v2")
                print("✓ Initialized SentenceTransformer in AlertEngine")
            except Exception as e:
                print(f"⚠ Failed to load SentenceTransformer in AlertEngine: {e}")

    def add_frame_to_history(self, frame: Dict[str, Any]):
        """Add frame to history for pattern detection"""
        self.frame_history[frame['frame_id']] = frame

    def _get_frame_hour(self, timestamp: str) -> int:
        """Extract hour from a timestamp string with graceful fallback."""
        if not timestamp:
            return 0

        normalized_timestamp = timestamp.replace("Z", "+00:00")
        try:
            return datetime.fromisoformat(normalized_timestamp).hour
        except (ValueError, TypeError):
            pass

        for separator in (" ", "T"):
            if separator in timestamp:
                timestamp = timestamp.split(separator, 1)[1]
                break

        try:
            return int(timestamp.split(":", 1)[0])
        except (ValueError, IndexError):
            return 0

    def _loads_json_object(self, text: str) -> Optional[Dict[str, Any]]:
        """Load the first JSON object from a model response."""
        if not text:
            return None
        import json
        try:
            parsed = json.loads(text)
            return parsed if isinstance(parsed, dict) else None
        except json.JSONDecodeError:
            pass

        start = text.find("{")
        end = text.rfind("}")
        if start == -1 or end == -1 or end <= start:
            return None

        try:
            parsed = json.loads(text[start:end + 1])
        except json.JSONDecodeError:
            return None

        return parsed if isinstance(parsed, dict) else None

    def analyze_frame(self, frame: Dict[str, Any], previous_frames: List[Dict[str, Any]] = None) -> List[Alert]:
        """
        Analyze a frame and generate alerts if needed.

        Detection order:
          1. Rule-based checks (hour + activity_type + location keywords)
          2. Embedding-similarity boost (secondary, for richer descriptions)
        The LLM is used only to *enrich* alert messages on confirmed hits —
        it never decides whether an alert fires.

        Args:
            frame: Current frame data
            previous_frames: Historical frames for context

        Returns:
            List of alerts triggered
        """
        alerts = []

        # Add to history
        self.add_frame_to_history(frame)

        # --- Primary layer: deterministic rule checks ---
        rule_alerts = self._check_rules(frame)
        alerts.extend(rule_alerts)

        # --- Secondary layer: contextual pattern checks ---
        if previous_frames:
            context_alerts = self._check_context(frame, previous_frames)
            alerts.extend(context_alerts)

        # --- Optional: LLM enriches message text on confirmed rule hits ---
        if alerts and self.llm_processor is not None and getattr(self.llm_processor, "llm", None) is not None:
            for alert in alerts:
                try:
                    enrich_prompt = (
                        f"<|im_start|>system\n"
                        f"You are a drone security analyst. Write a single clear, factual alert message "
                        f"(1-2 sentences, no speculation) for the following confirmed security event.<|im_end|>\n"
                        f"<|im_start|>user\n"
                        f"Alert type: {alert.alert_type}\n"
                        f"Location: {alert.location}\n"
                        f"Timestamp: {alert.timestamp}\n"
                        f"VLM description: {frame.get('description', '')}\n"
                        f"Detected objects: {', '.join(frame.get('objects', []))}\n"
                        f"Activity: {frame.get('activity_type', '')}\n"
                        f"Write only the alert message text.<|im_end|>\n"
                        f"<|im_start|>assistant\n"
                    )
                    enriched = self.llm_processor.query_llm(enrich_prompt).strip()
                    if enriched and len(enriched) > 10:
                        alert.message = enriched
                except Exception as e:
                    pass  # Keep original rule-generated message on failure

        # Store alerts
        self.alerts.extend(alerts)

        return alerts

    def _check_rules(self, frame: Dict[str, Any]) -> List[Alert]:
        """
        LLM-driven alert evaluation.

        Qwen2.5 receives the frame's timestamp, location, and BLIP-2 description
        and decides whether a security alert is warranted.  The LLM is the sole
        decision maker — no keyword lists, no hard-coded rules.

        Falls back to embedding-similarity screening only when the LLM is not loaded.
        """
        alerts = []
        timestamp = frame['timestamp']
        location  = frame['location']
        hour      = self._get_frame_hour(timestamp)
        description = frame.get('description', '')

        # --- Primary path: Qwen decides ---
        if self.llm_processor is not None and getattr(self.llm_processor, "llm", None) is not None:
            time_of_day = "night (off-hours)" if hour in (23, 0, 1, 2, 3, 4, 5, 6) else f"daytime (hour {hour})"

            prompt = (
                f"<|im_start|>system\n"
                f"You are a conservative drone security alert system. "
                f"Analyze the scene and decide if a security alert is needed. "
                f"Be strict: normal daytime activity (vehicles, people going about their day, "
                f"buildings, roads, fields) does NOT warrant an alert. "
                f"Only flag genuine threats: a person loitering at night, a perimeter breach, "
                f"or a suspicious vehicle during off-hours.\n"
                f"Return ONLY valid JSON. If no threat: {{\"alert\": false}}\n"
                f"If threat: {{\"alert\": true, \"alert_type\": \"loitering_midnight|perimeter_breach|night_vehicle\", "
                f"\"severity\": \"LOW|MEDIUM|HIGH|CRITICAL\", \"threat_score\": 1-10, "
                f"\"message\": \"one sentence factual description of the threat\"}}<|im_end|>\n"
                f"<|im_start|>user\n"
                f"Time: {time_of_day}\n"
                f"Location: {location}\n"
                f"Scene (from drone camera): {description}\n"
                f"<|im_end|>\n"
                f"<|im_start|>assistant\n"
            )

            try:
                response = self.llm_processor.query_llm(prompt)
                parsed = self._loads_json_object(response)
                if parsed and isinstance(parsed, dict) and parsed.get("alert"):
                    alerts.append(Alert(
                        frame_id=frame['frame_id'],
                        alert_type=parsed.get("alert_type", "suspicious_activity"),
                        severity=parsed.get("severity", "MEDIUM"),
                        threat_score=int(parsed.get("threat_score", 5)),
                        message=parsed.get("message", "Suspicious activity detected"),
                        timestamp=timestamp,
                        location=location,
                    ))
            except Exception as e:
                print(f"⚠ LLM alert evaluation failed: {e}")
            # If LLM loaded but returned no alert (or failed) → no false positive
            return alerts

        # --- Fallback: embedding similarity (no LLM available) ---
        if self.embed_model is not None and util is not None and description:
            try:
                alert_conditions = {
                    "loitering_midnight": {
                        "phrase": "a person is standing or loitering near a building or gate at night",
                        "severity": self.config.loitering_severity,
                        "threat_score": self.config.loitering_threat_score,
                        "time_gate": lambda h: h in self.config.loitering_hours,
                    },
                    "perimeter_breach": {
                        "phrase": "a person or vehicle is near a fence, gate, wall, or restricted perimeter area",
                        "severity": self.config.perimeter_severity,
                        "threat_score": self.config.perimeter_threat_score,
                        "time_gate": lambda h: True,
                    },
                    "night_vehicle": {
                        "phrase": "a car or truck is moving or parked near a gate or road at night",
                        "severity": self.config.night_vehicle_severity,
                        "threat_score": self.config.night_vehicle_threat_score,
                        "time_gate": lambda h: h in self.config.night_vehicle_hours,
                    },
                }
                desc_emb = self.embed_model.encode(description, convert_to_tensor=True)
                for alert_type, cond in alert_conditions.items():
                    if not cond["time_gate"](hour):
                        continue
                    cond_emb = self.embed_model.encode(cond["phrase"], convert_to_tensor=True)
                    similarity = float(util.cos_sim(desc_emb, cond_emb)[0][0])
                    if similarity > 0.50:
                        alerts.append(Alert(
                            frame_id=frame['frame_id'],
                            alert_type=alert_type,
                            severity=cond["severity"],
                            threat_score=cond["threat_score"],
                            message=f"{alert_type.replace('_', ' ').title()} detected at {location} [similarity: {similarity:.2f}]",
                            timestamp=timestamp,
                            location=location,
                        ))
            except Exception as e:
                print(f"⚠ Embedding fallback failed: {e}")

        return alerts



    def _check_context(self, frame: Dict[str, Any], previous_frames: List[Dict[str, Any]]) -> List[Alert]:

        """
        LLM-enhanced contextual alerting.
        Detects patterns and anomalies in frame history.
        """
        alerts = []
        timestamp = frame['timestamp']
        location = frame['location']
        objects = frame.get('objects', [])
        
        # PATTERN 1: Repeat vehicle/object visits
        vehicle_visits = self._find_repeat_vehicle_visits(frame, previous_frames)
        if vehicle_visits:
            for vehicle_info in vehicle_visits:
                alert = Alert(
                    frame_id=frame['frame_id'],
                    alert_type="repeat_visit",
                    severity=self.config.repeat_visit_severity,
                    threat_score=self.config.repeat_visit_threat_score,
                    message=f"Repeat visit: {vehicle_info['vehicle']} entered at {vehicle_info['first_time']} and {timestamp}",
                    timestamp=timestamp,
                    location=location
                )
                alerts.append(alert)
        
        # PATTERN 2: Suspicious dwell time
        dwell_alerts = self._check_dwell_time(frame, previous_frames)
        alerts.extend(dwell_alerts)
        
        return alerts

    def _find_repeat_vehicle_visits(
        self,
        current_frame: Dict[str, Any],
        previous_frames: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """
        Detect if a vehicle or person has visited multiple times.
        
        Returns list of repeat visit info.
        """
        repeats = []
        current_objects = current_frame.get('objects', [])
        
        # Look for common vehicle or person identifiers
        vehicle_keywords = {
            'truck', 'ford', 'f150', 'sedan', 'car', 'vehicle', 'blue',
            'silver', 'delivery', 'pickup', 'person', 'unknown person', 'employee'
        }
        
        current_vehicles = [obj for obj in current_objects if any(k in obj.lower() for k in vehicle_keywords)]
        
        if not current_vehicles:
            return repeats
        
        # Check if same vehicle/person appeared in previous frames
        for vehicle in current_vehicles:
            previous_visits = []
            for prev_frame in previous_frames:
                prev_objects = prev_frame.get('objects', [])
                # Look for vehicle/person name in previous frames
                if any(vehicle.lower() in str(obj).lower() or str(obj).lower() in vehicle.lower() for obj in prev_objects):
                    previous_visits.append({
                        'time': prev_frame['timestamp'],
                        'location': prev_frame['location']
                    })
            
            if previous_visits:
                repeats.append({
                    'vehicle': vehicle,
                    'first_time': previous_visits[0]['time'],
                    'current_time': current_frame['timestamp'],
                    'visit_count': len(previous_visits) + 1
                })
        
        return repeats

    def _check_dwell_time(
        self,
        current_frame: Dict[str, Any],
        previous_frames: List[Dict[str, Any]]
    ) -> List[Alert]:
        """
        Check if a vehicle/person has been stationary too long.
        """
        alerts = []
        location = current_frame['location']
        timestamp = current_frame['timestamp']
        objects = current_frame.get('objects', [])
        
        # Find frames with same object at same location
        same_location_frames = [f for f in previous_frames if f['location'] == location]
        
        if len(same_location_frames) >= self.config.dwell_time_min_frames:
            time_span = self._calculate_time_span(same_location_frames)
            
            if time_span > self.config.dwell_time_min_minutes:
                # Extract object name
                object_name = ", ".join(objects) if objects else "object"
                alert = Alert(
                    frame_id=current_frame['frame_id'],
                    alert_type="long_dwell",
                    severity=self.config.dwell_time_severity,
                    threat_score=self.config.dwell_time_threat_score,
                    message=f"{object_name} has been stationary at {location} for {time_span//60}+ hours",
                    timestamp=timestamp,
                    location=location
                )
                alerts.append(alert)
        
        return alerts

    def _calculate_time_span(self, frames: List[Dict[str, Any]]) -> int:
        """Calculate time span in minutes between first and last frame"""
        if not frames or len(frames) < 2:
            return 0
        
        try:
            first_time = datetime.fromisoformat(frames[0]['timestamp'])
            last_time = datetime.fromisoformat(frames[-1]['timestamp'])
            return int((last_time - first_time).total_seconds() / 60)
        except:
            return 0

    def get_all_alerts(self) -> List[Alert]:
        """Get all generated alerts"""
        return self.alerts

    def get_alerts_by_severity(self, severity: str) -> List[Alert]:
        """Filter alerts by severity"""
        return [a for a in self.alerts if a.severity == severity]

    def get_high_risk_alerts(self) -> List[Alert]:
        """Get all high-risk alerts (HIGH, CRITICAL)"""
        return [a for a in self.alerts if a.severity in ["HIGH", "CRITICAL"]]

    def get_summary_report(self) -> str:
        """Generate a text summary of all alerts"""
        if not self.alerts:
            return "No alerts generated during this period."
        
        summary = f"Alert Summary: {len(self.alerts)} total alerts\n"
        summary += f"- CRITICAL: {len(self.get_alerts_by_severity('CRITICAL'))}\n"
        summary += f"- HIGH: {len(self.get_alerts_by_severity('HIGH'))}\n"
        summary += f"- MEDIUM: {len(self.get_alerts_by_severity('MEDIUM'))}\n"
        summary += f"- LOW: {len(self.get_alerts_by_severity('LOW'))}\n\n"
        
        summary += "High-Risk Alerts:\n"
        for alert in self.get_high_risk_alerts():
            summary += f"  [{alert.timestamp}] {alert.severity}: {alert.message}\n"
        
        return summary


if __name__ == "__main__":
    # Test alert engine
    engine = AlertEngine()
    
    # Simulate frame analysis
    test_frame = {
        "frame_id": 1,
        "timestamp": "2026-06-13 00:01:00",
        "location": "Main Gate",
        "description": "Unknown person loitering",
        "objects": ["person"],
        "activity_type": "person"
    }
    
    alerts = engine.analyze_frame(test_frame)
    print(f"Generated {len(alerts)} alerts:")
    for alert in alerts:
        print(f"  [{alert.severity}] {alert.message}")
    
    print(f"\n{engine.get_summary_report()}")
