"""
Alert Engine: Hybrid alert system combining rules and LLM-based analysis
"""
from typing import Dict, List, Any, Optional
from dataclasses import dataclass
from datetime import datetime, timedelta


@dataclass
class Alert:
    """Alert generated by the system"""
    frame_id: int
    alert_type: str  # "loitering", "repeat_visit", "unusual_time", etc.
    severity: str  # LOW, MEDIUM, HIGH, CRITICAL
    threat_score: int  # 1-10
    message: str
    timestamp: str
    location: str


class AlertEngine:
    """
    Hybrid alert system with rule-based and LLM-enhanced layers.
    
    Rule Layer: Hard triggers based on predefined rules
    LLM Layer: Contextual analysis using frame history
    """

    def __init__(self):
        self.alerts: List[Alert] = []
        self.frame_history: Dict[int, Dict[str, Any]] = {}

    def add_frame_to_history(self, frame: Dict[str, Any]):
        """Add frame to history for pattern detection"""
        self.frame_history[frame['frame_id']] = frame

    def _get_frame_hour(self, timestamp: str) -> int:
        """Extract hour from a timestamp string with graceful fallback."""
        if not timestamp:
            return 0

        normalized_timestamp = timestamp.replace("Z", "+00:00")
        try:
            return datetime.fromisoformat(normalized_timestamp).hour
        except (ValueError, TypeError):
            pass

        for separator in (" ", "T"):
            if separator in timestamp:
                timestamp = timestamp.split(separator, 1)[1]
                break

        try:
            return int(timestamp.split(":", 1)[0])
        except (ValueError, IndexError):
            return 0

    def analyze_frame(self, frame: Dict[str, Any], previous_frames: List[Dict[str, Any]] = None) -> List[Alert]:
        """
        Analyze a frame and generate alerts if needed.
        
        Args:
            frame: Current frame data
            previous_frames: Historical frames for context
        
        Returns:
            List of alerts triggered
        """
        alerts = []
        
        # Add to history
        self.add_frame_to_history(frame)
        
        # Apply rule-based checks
        rule_alerts = self._check_rules(frame)
        alerts.extend(rule_alerts)
        
        # Apply LLM-enhanced contextual checks (if previous frames provided)
        if previous_frames:
            context_alerts = self._check_context(frame, previous_frames)
            alerts.extend(context_alerts)
        
        # Store alerts
        self.alerts.extend(alerts)
        
        return alerts

    def _check_rules(self, frame: Dict[str, Any]) -> List[Alert]:
        """
        Rule-based alerting layer.
        Triggers on hard conditions.
        """
        alerts = []
        timestamp = frame['timestamp']
        location = frame['location']
        hour = self._get_frame_hour(timestamp)
        activity_type = frame.get('activity_type', 'unknown')
        objects = frame.get('objects', [])
        
        # RULE 1: Loitering at midnight
        if hour >= 23 or hour <= 2:  # Midnight to 2 AM
            if activity_type == "person":
                alert = Alert(
                    frame_id=frame['frame_id'],
                    alert_type="loitering_midnight",
                    severity="HIGH",
                    threat_score=8,
                    message=f"Person loitering at {location} at {timestamp} (off-hours activity)",
                    timestamp=timestamp,
                    location=location
                )
                alerts.append(alert)
        
        # RULE 2: Suspicious perimeter activity
        if "perimeter" in location.lower() or "fence" in location.lower():
            if activity_type == "person":
                alert = Alert(
                    frame_id=frame['frame_id'],
                    alert_type="perimeter_breach",
                    severity="MEDIUM",
                    threat_score=6,
                    message=f"Person detected at {location} (perimeter security concern)",
                    timestamp=timestamp,
                    location=location
                )
                alerts.append(alert)
        
        # RULE 3: Unusual nighttime vehicle activity (vehicle at odd hour)
        if hour >= 23 or hour <= 6:  # Night hours
            if activity_type in ["vehicle", "vehicle+person"]:
                alert = Alert(
                    frame_id=frame['frame_id'],
                    alert_type="night_vehicle",
                    severity="LOW",
                    threat_score=3,
                    message=f"Vehicle activity at {location} during off-hours ({timestamp})",
                    timestamp=timestamp,
                    location=location
                )
                alerts.append(alert)
        
        return alerts

    def _check_context(self, frame: Dict[str, Any], previous_frames: List[Dict[str, Any]]) -> List[Alert]:
        """
        LLM-enhanced contextual alerting.
        Detects patterns and anomalies in frame history.
        """
        alerts = []
        timestamp = frame['timestamp']
        location = frame['location']
        objects = frame.get('objects', [])
        
        # PATTERN 1: Repeat vehicle visits
        vehicle_visits = self._find_repeat_vehicle_visits(frame, previous_frames)
        if vehicle_visits:
            for vehicle_info in vehicle_visits:
                alert = Alert(
                    frame_id=frame['frame_id'],
                    alert_type="repeat_visit",
                    severity="MEDIUM",
                    threat_score=5,
                    message=f"Repeat visit: {vehicle_info['vehicle']} entered at {vehicle_info['first_time']} and {timestamp}",
                    timestamp=timestamp,
                    location=location
                )
                alerts.append(alert)
        
        # PATTERN 2: Suspicious dwell time
        dwell_alerts = self._check_dwell_time(frame, previous_frames)
        alerts.extend(dwell_alerts)
        
        return alerts

    def _find_repeat_vehicle_visits(
        self,
        current_frame: Dict[str, Any],
        previous_frames: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """
        Detect if a vehicle has visited multiple times.
        
        Returns list of repeat vehicle info.
        """
        repeats = []
        current_objects = current_frame.get('objects', [])
        
        # Look for common vehicle identifiers
        vehicle_keywords = {
            'truck', 'ford', 'f150', 'sedan', 'car', 'vehicle', 'blue',
            'silver', 'delivery', 'pickup'
        }
        
        current_vehicles = [obj for obj in current_objects if obj.lower() in vehicle_keywords]
        
        if not current_vehicles:
            return repeats
        
        # Check if same vehicle appeared in previous frames
        for vehicle in current_vehicles:
            previous_visits = []
            for prev_frame in previous_frames:
                prev_objects = prev_frame.get('objects', [])
                # Look for vehicle name in previous frames
                if any(vehicle.lower() in str(obj).lower() for obj in prev_objects):
                    previous_visits.append({
                        'time': prev_frame['timestamp'],
                        'location': prev_frame['location']
                    })
            
            if previous_visits:
                repeats.append({
                    'vehicle': vehicle,
                    'first_time': previous_visits[0]['time'],
                    'current_time': current_frame['timestamp'],
                    'visit_count': len(previous_visits) + 1
                })
        
        return repeats

    def _check_dwell_time(
        self,
        current_frame: Dict[str, Any],
        previous_frames: List[Dict[str, Any]]
    ) -> List[Alert]:
        """
        Check if a vehicle/person has been stationary too long.
        """
        alerts = []
        location = current_frame['location']
        timestamp = current_frame['timestamp']
        objects = current_frame.get('objects', [])
        
        # Find frames with same object at same location
        same_location_frames = [f for f in previous_frames if f['location'] == location]
        
        if len(same_location_frames) >= 3:  # 3+ frames at same location
            time_span = self._calculate_time_span(same_location_frames)
            
            # If object stayed >4 hours, flag as long dwell
            if time_span > 240:  # 4 hours in minutes
                # Extract object name
                object_name = ", ".join(objects) if objects else "object"
                alert = Alert(
                    frame_id=current_frame['frame_id'],
                    alert_type="long_dwell",
                    severity="LOW",
                    threat_score=4,
                    message=f"{object_name} has been stationary at {location} for {time_span//60}+ hours",
                    timestamp=timestamp,
                    location=location
                )
                alerts.append(alert)
        
        return alerts

    def _calculate_time_span(self, frames: List[Dict[str, Any]]) -> int:
        """Calculate time span in minutes between first and last frame"""
        if not frames or len(frames) < 2:
            return 0
        
        try:
            first_time = datetime.fromisoformat(frames[0]['timestamp'])
            last_time = datetime.fromisoformat(frames[-1]['timestamp'])
            return int((last_time - first_time).total_seconds() / 60)
        except:
            return 0

    def get_all_alerts(self) -> List[Alert]:
        """Get all generated alerts"""
        return self.alerts

    def get_alerts_by_severity(self, severity: str) -> List[Alert]:
        """Filter alerts by severity"""
        return [a for a in self.alerts if a.severity == severity]

    def get_high_risk_alerts(self) -> List[Alert]:
        """Get all high-risk alerts (HIGH, CRITICAL)"""
        return [a for a in self.alerts if a.severity in ["HIGH", "CRITICAL"]]

    def get_summary_report(self) -> str:
        """Generate a text summary of all alerts"""
        if not self.alerts:
            return "No alerts generated during this period."
        
        summary = f"Alert Summary: {len(self.alerts)} total alerts\n"
        summary += f"- CRITICAL: {len(self.get_alerts_by_severity('CRITICAL'))}\n"
        summary += f"- HIGH: {len(self.get_alerts_by_severity('HIGH'))}\n"
        summary += f"- MEDIUM: {len(self.get_alerts_by_severity('MEDIUM'))}\n"
        summary += f"- LOW: {len(self.get_alerts_by_severity('LOW'))}\n\n"
        
        summary += "High-Risk Alerts:\n"
        for alert in self.get_high_risk_alerts():
            summary += f"  [{alert.timestamp}] {alert.severity}: {alert.message}\n"
        
        return summary


if __name__ == "__main__":
    # Test alert engine
    engine = AlertEngine()
    
    # Simulate frame analysis
    test_frame = {
        "frame_id": 1,
        "timestamp": "2026-06-13 00:01:00",
        "location": "Main Gate",
        "description": "Unknown person loitering",
        "objects": ["person"],
        "activity_type": "person"
    }
    
    alerts = engine.analyze_frame(test_frame)
    print(f"Generated {len(alerts)} alerts:")
    for alert in alerts:
        print(f"  [{alert.severity}] {alert.message}")
    
    print(f"\n{engine.get_summary_report()}")
